// Skill 7 — Report Generation.
// Produces a stakeholder-ready Markdown report (and HTML via marked) containing every
// required section: direct answer, executive summary, non-technical explanation,
// technical methodology, sources used/rejected, dataset summary, key findings,
// limitations, confidence, recommendations, and an appendix with field definitions.

import { Plan, EvaluatedSource, Dataset, AnalysisResult, AuditEvent } from './types';
import { datasetDictionary } from './transform';

export interface ReportInput {
  question: string;
  plan: Plan;
  sources: EvaluatedSource[];
  datasets: Dataset[];
  analysis: AnalysisResult;
  auditTrail: AuditEvent[];
  generatedAt: string;
  mockMode: boolean;
}

function fmt(n: unknown, digits = 2): string {
  return typeof n === 'number' && isFinite(n) ? n.toFixed(digits) : 'n/a';
}

function forecastSection(a: AnalysisResult): string {
  const d = a.details as Record<string, any>;
  if (!d.point) return '';
  const range80 = d.range80 as [number, number] | undefined;
  const range95 = d.range95 as [number, number] | undefined;
  const bt = d.backtest as Record<string, number> | undefined;
  const comp = d.components as Record<string, number> | undefined;
  return `
## Direct Answer

**Central estimate for ${d.target ?? 'the target'} at the ${d.horizon_days}-day horizon: ~$${fmt(d.point)}** (last observed: $${fmt(d.last_close)} on ${d.as_of}).

| Interval | Range |
| --- | --- |
| Likely range (80%) | $${fmt(range80?.[0])} – $${fmt(range80?.[1])} |
| Wide range (95%) | $${fmt(range95?.[0])} – $${fmt(range95?.[1])} |

Treat the **range as the answer**, not the point. Short-horizon commodity prices behave close to a random walk; the interval reflects observed volatility, and unforeseeable news can move prices outside it.

### Model components (per-method estimates, $/bbl)

| Method | Estimate | Backtest MAE |
| --- | --- | --- |
${Object.entries(comp ?? {}).map(([k, v]) => `| ${k} | $${fmt(v)} | ${bt && k in bt ? fmt(bt[k]) : '—'} |`).join('\n')}

Backtest = walk-forward mean absolute error at the same horizon over the recent history. The final estimate weights the best-performing baseline(s)${d.futures_used ? ' anchored by the futures curve' : ''}.

### Qualitative signals (kept separate from the numeric forecast)

${d.sentiment ? `News sentiment score: **${fmt((d.sentiment as any).score)}** (−1 bearish … +1 bullish) across ${(d.sentiment as any).n_headlines} headlines (${(d.sentiment as any).positive} bullish / ${(d.sentiment as any).negative} bearish). ${(d.sentiment as any).note ?? ''}` : 'No headline data available.'}
`;
}

export function generateMarkdownReport(input: ReportInput): string {
  const { question, plan, sources, datasets, analysis, generatedAt, mockMode } = input;
  const selected = sources.filter((s) => s.selected);
  const rejected = sources.filter((s) => !s.selected);
  const d = analysis.details as Record<string, any>;

  return `# Research Report: ${question}

*Generated by Prospect on ${generatedAt}${mockMode ? ' — **MOCK MODE: all data below is bundled demo data, clearly labeled `is_mock=true`. This is NOT a real market forecast.** Connect live APIs (see README) to produce real analyses.' : ''}*

${forecastSection(analysis)}

## Executive Summary

${analysis.summary}

**Confidence level: ${analysis.confidence.toUpperCase()}** — ${analysis.confidenceReasons.join(' ')}

## Non-Technical Explanation

We read your question as: *estimate ${plan.targetVariable} over the horizon "${plan.timeHorizon.label}"*. We gathered ${datasets.length} dataset(s) from ${selected.length} vetted public sources, cleaned them into analysis-ready tables, and compared several simple, honest forecasting approaches instead of trusting a single complex model. Think of it like asking several sensible advisors — "assume tomorrow looks like today", "follow the recent trend", "trust what the futures market is pricing in" — checking which advisor has been most accurate recently, and then reporting a realistic range rather than a single number, because nobody can predict ${plan.topic} precisely a ${plan.timeHorizon.label} out. News and OPEC-style signals are summarized separately so opinion never silently contaminates the numbers.

## Technical Methodology

- **Question parsing (Skill 1):** task type \`${plan.taskType}\`, target \`${plan.targetVariable}\`, horizon \`${plan.timeHorizon.label}\` (${plan.timeHorizon.days ?? 'n/a'} days), domain \`${plan.domain}\`.
- **Search (Skill 2):** ${plan.searchQueries.length} targeted queries; sources classified into reliability tiers 1–4.
- **Evaluation (Skill 3):** weighted scoring (authority 0.30, relevance 0.25, data availability 0.20, accessibility 0.15, recency 0.05, licensing 0.05); selection threshold 0.55; paywalled/blocked/Tier-4 sources rejected with reasons.
- **Collection (Skill 4):** ${mockMode ? 'mock providers (no live fetches)' : 'official APIs > CSV downloads > RSS > static HTML tables; robots.txt-checked, rate-limited, snapshot-archived'}.
- **Transformation (Skill 5):** snake_case normalization, type inference, ISO dates, dedup by date key, no imputation, provenance columns on every row.
- **Analysis (Skill 6):** method \`${analysis.method}\` (engine v${analysis.engineVersion}). ${d.point ? `Baselines (naive, SMA-5, drift) walk-forward backtested at the ${d.horizon_days}-day horizon; interval from realized volatility of log returns (σ_daily=${fmt(d.volatility?.daily_sigma, 4)}) scaled by √h.` : ''}

## Data Sources Used

| Source | Tier | Category | Score | Why selected |
| --- | --- | --- | --- | --- |
${selected.map((s) => `| [${s.title.replace(/\|/g, '/')}](${s.url}) | ${s.tier} | ${s.category} | ${s.totalScore} | ${s.reason.replace(/\|/g, '/')} |`).join('\n')}

## Data Sources Rejected

| Source | Tier | Score | Why rejected |
| --- | --- | --- | --- |
${rejected.map((s) => `| [${s.title.replace(/\|/g, '/')}](${s.url}) | ${s.tier} | ${s.totalScore} | ${s.reason.replace(/\|/g, '/')} |`).join('\n') || '| (none) | | | |'}

## CSV Dataset Summary

${datasets.map((ds) => `- **${ds.name}.csv** — ${ds.description}. Columns: ${ds.columns.map((c) => `\`${c.name}\``).join(', ')}. Quality notes: ${ds.qualityNotes.join(' ')}`).join('\n')}

All CSVs carry provenance columns (\`source_name\`, \`source_url\`, \`collected_at\`, \`is_mock\`).

## Key Findings

${analysis.insights.map((i) => `- **[${i.kind}] ${i.title}** — ${i.body}`).join('\n')}

## Limitations

${analysis.limitations.map((l) => `- ${l}`).join('\n')}
- Observational public data supports correlational evidence only; no causal claims are made.
${mockMode ? '- **All findings derive from mock data and demonstrate the workflow, not the market.**' : ''}

## Confidence Assessment

**${analysis.confidence.toUpperCase()}.** ${analysis.confidenceReasons.join(' ')}

## Recommended Next Actions

${analysis.insights.filter((i) => i.kind === 'recommendation').map((i) => `- ${i.body}`).join('\n') || '- Review findings and schedule a recurring run to monitor changes.'}
- Schedule this research as a recurring run (e.g. every Monday 07:00) to track how the outlook evolves.
${mockMode ? '- Connect EIA/FRED API keys and a real search provider, then re-run for live results.' : ''}

## Appendix A — Field Definitions

${datasets.map((ds) => `### ${ds.name}\n\n| Field | Original | Type | Unit | Description |\n| --- | --- | --- | --- | --- |\n${ds.columns.map((c) => `| \`${c.name}\` | ${c.originalName} | ${c.type} | ${c.unit ?? ''} | ${c.description.replace(/\|/g, '/')} |`).join('\n')}`).join('\n\n')}

## Appendix B — Methodology Details & Assumptions

${analysis.assumptions.map((a) => `- ${a}`).join('\n')}
${datasets.flatMap((ds) => ds.assumptions).filter((v, i, a) => a.indexOf(v) === i).map((a) => `- ${a}`).join('\n')}
`;
}

export function reportSummaryLine(input: ReportInput): string {
  const dd = input.analysis.details as Record<string, any>;
  return dd.point
    ? `Central estimate ~$${fmt(dd.point)} (80% range $${fmt(dd.range80?.[0])}–$${fmt(dd.range80?.[1])}), confidence ${input.analysis.confidence}.`
    : input.analysis.summary.slice(0, 200);
}

export { datasetDictionary };
